DEVICE: cuda
CACHE_DIR: ./data/cache
MODEL_DIR: ./data/models
DATA_LOOKBACK_DAYS: 730
SAMPLE_WEIGHT_HALFLIFE: 60
MIN_SHARPE_RATIO: 0.5
MAX_POSITIONS: 10
MAX_POSITION_SIZE: 0.1
OPENAI_API_KEY: null
ALPACA_API_KEY: null
ALPACA_SECRET_KEY: null
ALPACA_BASE_URL: https://paper-api.alpaca.markets
